- name: Create mtg directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/mtg
    - /etc/mtg

- name: Get list of releases
  uri:
    url: https://api.github.com/repos/9seconds/mtg/releases/latest
    return_content: yes
  register: mtg_releases

- name: Check for update
  debug:
    msg: "Newer version {{ mtg_releases.json.tag_name }} available, consider updating"
  when: mtg_releases.json.tag_name != mtg_version|string

- name: Download binary
  get_url:
    url: "https://github.com/9seconds/mtg/releases/download/{{ mtg_version }}/mtg-linux-amd64"
    checksum: "{{ mtg_checksum }}"
    dest: /opt/mtg/mtg-linux-amd64
  notify: restart mtg

- name: "Create VERSION file"
  copy:
    content: "{{ mtg_version }}"
    dest: "/etc/mtg/VERSION"
    mode: 0600
