- name: Create mtg directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/mtg
    - /etc/mtg

- name: Download binary
  get_url:
    url: "https://github.com/9seconds/mtg/releases/download/v{{ mtg_version }}/mtg-linux-{{ mtg_architecture | default('amd64') }}"
    checksum: "{{ mtg_checksum }}"
    dest: /opt/mtg/mtg-linux-amd64
    mode: 0740
  notify: restart mtg

- name: Upload systemd unit file
  template:
    src: mtg.service.j2
    dest: /etc/systemd/system/mtg.service
  notify:
    - systemd daemon-reload
    - restart mtg

- name: "Create VERSION file"
  copy:
    content: "{{ mtg_version }}"
    dest: "/etc/mtg/VERSION"
    mode: 0600
